### ISSUE TITLE
Some problems between ROS and python3?

### ISSUE THREAD

**Issue by zhuhu00** [bxh1/VIDO-SLAM#2]
Thank you for such excellent work! I am very interested in this work, but some problems occur when I try to build your code. I guess it's the version between ROS and python3, I want to ask what is your code environment? 

My computer is Ubuntu18.04 with Conda or python. Or can you give more information about the environment?

**Comment by bxh1** [comment]
conda or python environment can refer to thirdparty repo(flownet, monodepth2)
