### ISSUE TITLE
where the model "network-default.pytorch"

### ISSUE THREAD

**Issue by Hello-Water** [bxh1/VIDO-SLAM#5]
Hello, can you provide the models in "flow_net" and "mono_depth2", or how to get them? Should I train them myself?
"
FileNotFoundError: [Errno 2] No such file or directory: '/VIDO-SLAM/src/thirdparty/flow_net/src/models/network-default.pytorch'
"

**Comment by bxh1** [comment]
You can refer to the download link in the thirdparty repo 
https://github.com/sniklaus/pytorch-liteflownet/blob/93183f5aefd025ce33d2750d3be50b3b7d7c20f6/run.py#L297
